Repository SmartPhoenix/Persistent-Kingdoms, pull requests merged in 2018-02, with the labels that each got.

#13 Added Outlaw Chat
  module_constants.py
  module_mission_templates.py
  module_scripts.py
Labels: need code review

#19 Update gitignore
  .gitignore
Labels: Minor, Task

#15 Removed Default Gear
  .gitignore
  module_troops.py
Labels: need testing

#52 Adjusted arrow ammo amounts
  module_items.py
Labels: need testing

#59 Allows players to poll themselves lord in empty factions
  module_constants.py
  module_presentations.py
  module_scripts.py
Labels: bug, need testing

#65 Teleport to you
  header_common.py
  module_presentations.py
  module_scripts.py
  module_strings.py
Labels: need testing
