Repository SmartPhoenix/Persistent-Kingdoms, pull requests merged in 2018-03, with the labels that each got.

#71 Optional Spectator Disable
  module_mission_templates.py
  module_presentations.py
  module_scripts.py
Labels: need testing

#106 Prevent Lord Repoll
  module_presentations.py
  module_scripts.py
Labels: need testing

#93 Increased crafting times for ammo from default
  module_scene_props.py
Labels: need testing

#82 Disconnect Logs
  module_mission_templates.py
  module_strings.py
Labels: enhancement

#121 Key Notifications
  module_scripts.py
  module_strings.py
Labels: need testing

#122 Teleport Horses
  module_scripts.py
Labels: need testing

#124 Adjusted import times
  module_scene_props.py
Labels: need testing

#125 Basic Name Labels
  module_constants.py
  module_presentations.py
  module_strings.py
Labels: need testing

#115 Doubled Item Purchase Offset
  module_scene_props.py
Labels: enhancement

#127 Poll Cooldown
  module_constants.py
  module_presentations.py
  module_scripts.py
Labels: need testing

#134 Added "you were kicked" messages and logs
  module_scripts.py
  module_strings.py
Labels: need testing

#163 Typo Fixes in Local Pouch Reveal
  module_strings.py
Labels: Integrated

#156 Ta general logs
  module_constants.py
  module_items.py
  module_mission_templates.py
  module_scripts.py
  module_strings.py
Labels: need testing

#164 Gold Loot Changes
  module_scripts.py
Labels: Integrated

#153 Assign player in inactive factions to commoner on connection
  module_scripts.py
Labels: need testing

#181 Chest appears lockpicked message
  module_scripts.py
  module_strings.py
Labels: need testing
